import type { DietCategory, MealType } from "./constants";
import { getWeekNumber, getCurrentYear } from "./utils";

export interface Recipe {
  id: number;
  name: string;
  description: string;
  dietCategory: DietCategory;
  mealType: MealType;
  ingredients: { amount: number; unit: string; name: string }[];
  instructions: string[];
  prepTimeMinutes: number;
  cookTimeMinutes: number;
  servings: number;
  calories: number;
  proteinGrams: number;
  carbsGrams: number;
  fatGrams: number;
  imageUrl: string | null;
}

const allRecipes: Omit<Recipe, "id">[] = [
  // === KASVISRUOKA ===
  {
    name: "Pinaattikeitto",
    description: "Kermainen pinaattikeitto kananmunalla",
    dietCategory: "kasvisruoka",
    mealType: "lounas",
    ingredients: [
      { amount: 300, unit: "g", name: "tuore pinaatti" },
      { amount: 1, unit: "kpl", name: "sipuli" },
      { amount: 2, unit: "rkl", name: "voi" },
      { amount: 5, unit: "dl", name: "kasvisliemi" },
      { amount: 2, unit: "dl", name: "kerma" },
      { amount: 2, unit: "kpl", name: "kananmuna" },
    ],
    instructions: [
      "Kuullota pilkottu sipuli voissa kattilassa.",
      "Lisää pinaatti ja kasvisliemi. Keitä 5 minuuttia.",
      "Soseuta sauvasekoittimella tasaiseksi.",
      "Lisää kerma ja mausta suolalla ja pippurilla.",
      "Keitä kananmunat 8 minuuttia, puolita ja aseta keiton päälle.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 4,
    calories: 280,
    proteinGrams: 14,
    carbsGrams: 8,
    fatGrams: 22,
    imageUrl: null,
  },
  {
    name: "Kasvispasta",
    description: "Tomaattinen pasta grillatuilla kasviksilla",
    dietCategory: "kasvisruoka",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "pasta" },
      { amount: 2, unit: "kpl", name: "paprika" },
      { amount: 1, unit: "kpl", name: "kesäkurpitsa" },
      { amount: 200, unit: "g", name: "kirsikkatomaatit" },
      { amount: 2, unit: "rkl", name: "oliiviöljy" },
      { amount: 400, unit: "ml", name: "tomaattimurska" },
      { amount: 100, unit: "g", name: "parmesaani" },
    ],
    instructions: [
      "Keitä pasta pakkauksen ohjeen mukaan.",
      "Leikkaa paprikat ja kesäkurpitsa kuutioiksi.",
      "Paista kasvikset oliiviöljyssä pannulla kuumalla lämmöllä.",
      "Lisää kirsikkatomaatit ja tomaattimurska. Keitä 10 minuuttia.",
      "Sekoita pasta ja kastike. Tarjoile parmesaanin kera.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 4,
    calories: 450,
    proteinGrams: 18,
    carbsGrams: 62,
    fatGrams: 14,
    imageUrl: null,
  },
  {
    name: "Juustomunakas",
    description: "Täyteläinen munakas juustolla ja yrteillä",
    dietCategory: "kasvisruoka",
    mealType: "aamiainen",
    ingredients: [
      { amount: 3, unit: "kpl", name: "kananmuna" },
      { amount: 50, unit: "g", name: "emmental-juusto" },
      { amount: 1, unit: "rkl", name: "voi" },
      { amount: 1, unit: "rkl", name: "tuore tilli" },
      { amount: 1, unit: "dl", name: "maito" },
    ],
    instructions: [
      "Vatkaa munat ja maito keskenään.",
      "Sulata voi pannussa keskilämmöllä.",
      "Kaada munamassa pannuun ja anna hyytyä pohjasta.",
      "Ripottele raastettu juusto ja tilli päälle.",
      "Taita kahtia ja tarjoile heti.",
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    servings: 1,
    calories: 380,
    proteinGrams: 26,
    carbsGrams: 3,
    fatGrams: 30,
    imageUrl: null,
  },
  {
    name: "Kasvis-halloumisalaatti",
    description: "Raikas salaatti grillatulla halloumilla",
    dietCategory: "kasvisruoka",
    mealType: "lounas",
    ingredients: [
      { amount: 200, unit: "g", name: "halloumi" },
      { amount: 200, unit: "g", name: "salaattisekoitus" },
      { amount: 1, unit: "kpl", name: "avokado" },
      { amount: 150, unit: "g", name: "kirsikkatomaatit" },
      { amount: 1, unit: "kpl", name: "kurkku" },
      { amount: 2, unit: "rkl", name: "oliiviöljy" },
      { amount: 1, unit: "rkl", name: "sitruunamehu" },
    ],
    instructions: [
      "Leikkaa halloumi viipaleiksi ja grillaa pannulla kultaiseksi.",
      "Kokoa salaatti lautaselle.",
      "Viipaleoi avokado, tomaatit ja kurkku.",
      "Asettele grillattu halloumi päälle.",
      "Valuta oliiviöljy-sitruunakastike päälle.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 5,
    servings: 2,
    calories: 420,
    proteinGrams: 22,
    carbsGrams: 12,
    fatGrams: 34,
    imageUrl: null,
  },
  {
    name: "Kasviscurry",
    description: "Kookoskermalla maustettu kasvis-curry",
    dietCategory: "kasvisruoka",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "kukkakaali" },
      { amount: 2, unit: "kpl", name: "peruna" },
      { amount: 200, unit: "g", name: "pinaatti" },
      { amount: 400, unit: "ml", name: "kookosmaito" },
      { amount: 2, unit: "rkl", name: "currypaahto" },
      { amount: 3, unit: "dl", name: "riisi" },
    ],
    instructions: [
      "Pilko kukkakaali ja perunat kuutioiksi.",
      "Kuullota sipuli ja currypaahto kattilassa.",
      "Lisää kasvikset ja kookosmaito. Keitä 20 minuuttia.",
      "Lisää pinaatti lopussa ja mausta suolalla.",
      "Tarjoile riisin kanssa.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 4,
    calories: 380,
    proteinGrams: 10,
    carbsGrams: 48,
    fatGrams: 18,
    imageUrl: null,
  },
  {
    name: "Rahkapuuro marjoilla",
    description: "Proteiinipitoinen kaurapuuro rahkalla ja marjoilla",
    dietCategory: "kasvisruoka",
    mealType: "aamiainen",
    ingredients: [
      { amount: 1, unit: "dl", name: "kaurahiutale" },
      { amount: 2.5, unit: "dl", name: "vesi" },
      { amount: 1, unit: "dl", name: "rahka" },
      { amount: 1, unit: "dl", name: "mustikka" },
      { amount: 1, unit: "rkl", name: "hunaja" },
    ],
    instructions: [
      "Keitä kaurapuuro vedessä.",
      "Annostele kulhoon ja anna jäähtyä hieman.",
      "Lisää rahka päälle.",
      "Koristele mustikoilla ja hunajalla.",
    ],
    prepTimeMinutes: 2,
    cookTimeMinutes: 5,
    servings: 1,
    calories: 310,
    proteinGrams: 18,
    carbsGrams: 42,
    fatGrams: 8,
    imageUrl: null,
  },

  // === KASVISRUOKA VÄLIPALAT ===
  {
    name: "Hedelmärahka",
    description: "Raikas rahka tuoreilla hedelmillä",
    dietCategory: "kasvisruoka",
    mealType: "välipala",
    ingredients: [
      { amount: 2, unit: "dl", name: "maitorahka" },
      { amount: 1, unit: "kpl", name: "banaani" },
      { amount: 1, unit: "dl", name: "mustikka" },
      { amount: 1, unit: "rkl", name: "hunaja" },
    ],
    instructions: [
      "Annostele rahka kulhoon.",
      "Viipaloiti banaani ja lisää mustikat.",
      "Loruta hunaja päälle.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 220,
    proteinGrams: 16,
    carbsGrams: 32,
    fatGrams: 4,
    imageUrl: null,
  },
  {
    name: "Juustotikut ja hummus",
    description: "Kasvisjuustotikut hummusdippillä",
    dietCategory: "kasvisruoka",
    mealType: "välipala",
    ingredients: [
      { amount: 1, unit: "kpl", name: "porkkana" },
      { amount: 1, unit: "kpl", name: "kurkku" },
      { amount: 1, unit: "kpl", name: "paprika" },
      { amount: 3, unit: "rkl", name: "hummus" },
    ],
    instructions: [
      "Leikkaa kasvikset tikuiksi.",
      "Annostele hummus dippikuppiin.",
      "Dippaile ja nauti.",
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 160,
    proteinGrams: 6,
    carbsGrams: 18,
    fatGrams: 8,
    imageUrl: null,
  },
  {
    name: "Kasvisvoileipä",
    description: "Ruisleipä avokadolla ja tomaatilla iltapalaksi",
    dietCategory: "kasvisruoka",
    mealType: "iltapala",
    ingredients: [
      { amount: 1, unit: "viipale", name: "ruisleipä" },
      { amount: 0.5, unit: "kpl", name: "avokado" },
      { amount: 1, unit: "kpl", name: "tomaatti" },
      { amount: 1, unit: "tl", name: "sitruunamehu" },
    ],
    instructions: [
      "Murskaa avokado ja levitä leivän päälle.",
      "Lisää tomaattiviipaleet.",
      "Loruta sitruunamehua ja mausta suolalla.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 200,
    proteinGrams: 5,
    carbsGrams: 22,
    fatGrams: 12,
    imageUrl: null,
  },
  {
    name: "Marjasmoothie",
    description: "Raikas marjasmoothie jogurtilla",
    dietCategory: "kasvisruoka",
    mealType: "iltapala",
    ingredients: [
      { amount: 1, unit: "dl", name: "jogurtti" },
      { amount: 1, unit: "dl", name: "mustikka" },
      { amount: 1, unit: "dl", name: "mansikka" },
      { amount: 1, unit: "dl", name: "maito" },
    ],
    instructions: [
      "Laita kaikki ainekset tehosekoittimeen.",
      "Sekoita tasaiseksi.",
      "Tarjoile heti.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 150,
    proteinGrams: 8,
    carbsGrams: 22,
    fatGrams: 3,
    imageUrl: null,
  },

  // === LIHARUOKA ===
  {
    name: "Kanawokki",
    description: "Nopea kanawokki kasviksilla ja soijakastikkeella",
    dietCategory: "liharuoka",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "kananrintafilee" },
      { amount: 1, unit: "kpl", name: "paprika" },
      { amount: 1, unit: "kpl", name: "porkkana" },
      { amount: 100, unit: "g", name: "soijaitu" },
      { amount: 3, unit: "rkl", name: "soijakastike" },
      { amount: 1, unit: "rkl", name: "seesaminsiemen" },
      { amount: 3, unit: "dl", name: "riisi" },
    ],
    instructions: [
      "Keitä riisi ohjeen mukaan.",
      "Leikkaa kana suikaleiksi ja paista kuumalla pannulla.",
      "Lisää pilkotut kasvikset ja paista 3 minuuttia.",
      "Mausta soijakastikkeella.",
      "Tarjoile riisin kanssa ja ripottele seesaminsiemenet päälle.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 4,
    calories: 420,
    proteinGrams: 35,
    carbsGrams: 45,
    fatGrams: 10,
    imageUrl: null,
  },
  {
    name: "Lihapullat ja muusi",
    description: "Perinteiset lihapullat kermakastikkeella ja perunamuusilla",
    dietCategory: "liharuoka",
    mealType: "päivällinen",
    ingredients: [
      { amount: 500, unit: "g", name: "jauheliha" },
      { amount: 1, unit: "kpl", name: "kananmuna" },
      { amount: 0.5, unit: "dl", name: "korppujauho" },
      { amount: 1, unit: "dl", name: "maito" },
      { amount: 6, unit: "kpl", name: "peruna" },
      { amount: 2, unit: "dl", name: "kerma" },
    ],
    instructions: [
      "Sekoita jauheliha, muna, korppujauho ja maito.",
      "Muotoile pulliksi ja paista pannulla ruskeiksi.",
      "Keitä perunat ja survoo muusiksi kerman kanssa.",
      "Tee pannuun kermakastike paistinliemestä.",
      "Tarjoile lihapullat muusin ja kastikkeen kanssa.",
    ],
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    servings: 4,
    calories: 520,
    proteinGrams: 32,
    carbsGrams: 38,
    fatGrams: 28,
    imageUrl: null,
  },
  {
    name: "Kinkku-juustoleipä",
    description: "Paahdettu täysjyväleipä kinkulla ja juustolla",
    dietCategory: "liharuoka",
    mealType: "aamiainen",
    ingredients: [
      { amount: 2, unit: "viipale", name: "täysjyväleipä" },
      { amount: 4, unit: "viipale", name: "kinkku" },
      { amount: 2, unit: "viipale", name: "emmental" },
      { amount: 1, unit: "kpl", name: "tomaatti" },
      { amount: 1, unit: "tl", name: "voi" },
    ],
    instructions: [
      "Paahda leivät ja voitele.",
      "Aseta kinkku ja juusto päälle.",
      "Grillaa kunnes juusto sulaa.",
      "Lisää tomaattiviipaleet ja tarjoile.",
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    servings: 1,
    calories: 380,
    proteinGrams: 24,
    carbsGrams: 30,
    fatGrams: 18,
    imageUrl: null,
  },
  {
    name: "Broilerikeitto",
    description: "Lämmin broilerikeitto juureksilla",
    dietCategory: "liharuoka",
    mealType: "lounas",
    ingredients: [
      { amount: 300, unit: "g", name: "broilerinrintafilee" },
      { amount: 2, unit: "kpl", name: "porkkana" },
      { amount: 2, unit: "kpl", name: "peruna" },
      { amount: 1, unit: "kpl", name: "palsternakka" },
      { amount: 8, unit: "dl", name: "kanaliemi" },
      { amount: 1, unit: "dl", name: "ruokakerma" },
    ],
    instructions: [
      "Keitä broileri liemessä kypsäksi ja revit palasiksi.",
      "Pilko juurekset kuutioiksi ja lisää liemeen.",
      "Keitä kunnes juurekset ovat kypsiä.",
      "Lisää kerma ja broilerin palat takaisin.",
      "Mausta suolalla ja pippurilla.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 4,
    calories: 310,
    proteinGrams: 28,
    carbsGrams: 22,
    fatGrams: 12,
    imageUrl: null,
  },
  {
    name: "Jauheliha-makaronilaatikko",
    description: "Klassinen suomalainen makaronilaatikko",
    dietCategory: "liharuoka",
    mealType: "lounas",
    ingredients: [
      { amount: 400, unit: "g", name: "jauheliha" },
      { amount: 400, unit: "g", name: "makaroni" },
      { amount: 5, unit: "dl", name: "maito" },
      { amount: 3, unit: "kpl", name: "kananmuna" },
      { amount: 1, unit: "kpl", name: "sipuli" },
    ],
    instructions: [
      "Keitä makaronit al denteksi.",
      "Paista jauheliha sipulin kanssa.",
      "Sekoita makaronit ja jauheliha uunivuokaan.",
      "Vatkaa munat ja maito, kaada päälle.",
      "Paista uunissa 200°C noin 40 minuuttia.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 45,
    servings: 6,
    calories: 480,
    proteinGrams: 30,
    carbsGrams: 50,
    fatGrams: 18,
    imageUrl: null,
  },
  {
    name: "Kananmunakokkeli",
    description: "Pehmeä kokkeli tuoreyrteillä",
    dietCategory: "liharuoka",
    mealType: "aamiainen",
    ingredients: [
      { amount: 3, unit: "kpl", name: "kananmuna" },
      { amount: 1, unit: "rkl", name: "voi" },
      { amount: 1, unit: "rkl", name: "ruohosipuli" },
      { amount: 0.5, unit: "dl", name: "maito" },
      { amount: 2, unit: "viipale", name: "ruisleipä" },
    ],
    instructions: [
      "Vatkaa munat ja maito.",
      "Sulata voi pannussa miedolla lämmöllä.",
      "Kaada munamassa ja sekoita hitaasti spatulalla.",
      "Nosta pois tulelta kun kokkeli on vielä hieman pehmeää.",
      "Ripottele ruohosipuli päälle. Tarjoile ruisleivän kanssa.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 5,
    servings: 1,
    calories: 350,
    proteinGrams: 22,
    carbsGrams: 24,
    fatGrams: 20,
    imageUrl: null,
  },

  // === LIHARUOKA VÄLIPALAT ===
  {
    name: "Kananpojan wrap",
    description: "Nopea kanawrap salaatilla",
    dietCategory: "liharuoka",
    mealType: "välipala",
    ingredients: [
      { amount: 100, unit: "g", name: "grillattua kanaa" },
      { amount: 1, unit: "kpl", name: "tortilla" },
      { amount: 50, unit: "g", name: "salaatti" },
      { amount: 1, unit: "rkl", name: "majoneesi" },
    ],
    instructions: [
      "Levitä majoneesi tortillalle.",
      "Lisää kanasuikaleet ja salaatti.",
      "Kääri ja halkaisi.",
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 250,
    proteinGrams: 20,
    carbsGrams: 22,
    fatGrams: 10,
    imageUrl: null,
  },
  {
    name: "Kinkkurullat",
    description: "Kinkkurullat tuorejuustolla",
    dietCategory: "liharuoka",
    mealType: "välipala",
    ingredients: [
      { amount: 4, unit: "viipale", name: "kinkku" },
      { amount: 2, unit: "rkl", name: "tuorejuusto" },
      { amount: 4, unit: "kpl", name: "suolakurkku" },
    ],
    instructions: [
      "Levitä tuorejuustoa kinkkuviipaleen päälle.",
      "Aseta suolakurkku keskelle.",
      "Kääri rullaksi.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 180,
    proteinGrams: 14,
    carbsGrams: 4,
    fatGrams: 12,
    imageUrl: null,
  },
  {
    name: "Kanakeitto (jäännös)",
    description: "Lämmitettyä kanakeittoa iltapalaksi",
    dietCategory: "liharuoka",
    mealType: "iltapala",
    ingredients: [
      { amount: 3, unit: "dl", name: "kanakeitto" },
      { amount: 1, unit: "viipale", name: "ruisleipä" },
    ],
    instructions: [
      "Lämmitä keitto kattilassa tai mikrossa.",
      "Tarjoile ruisleivän kanssa.",
    ],
    prepTimeMinutes: 2,
    cookTimeMinutes: 3,
    servings: 1,
    calories: 200,
    proteinGrams: 15,
    carbsGrams: 20,
    fatGrams: 6,
    imageUrl: null,
  },
  {
    name: "Meetvurstileipä",
    description: "Ruisleipä meetvurstilla ja kurkkuviipaleilla",
    dietCategory: "liharuoka",
    mealType: "iltapala",
    ingredients: [
      { amount: 1, unit: "viipale", name: "ruisleipä" },
      { amount: 4, unit: "viipale", name: "meetvursti" },
      { amount: 0.5, unit: "kpl", name: "kurkku" },
      { amount: 1, unit: "tl", name: "voi" },
    ],
    instructions: [
      "Voitele ruisleipä.",
      "Aseta meetvurstiviipaleet päälle.",
      "Lisää kurkkuviipaleet.",
    ],
    prepTimeMinutes: 2,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 220,
    proteinGrams: 10,
    carbsGrams: 18,
    fatGrams: 12,
    imageUrl: null,
  },

  // === VEGAANI ===
  {
    name: "Tofucurry",
    description: "Mausteinen tofucurry kookoskermalla",
    dietCategory: "vegaani",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "kiinteä tofu" },
      { amount: 400, unit: "ml", name: "kookosmaito" },
      { amount: 2, unit: "rkl", name: "currypaahto" },
      { amount: 200, unit: "g", name: "pinaatti" },
      { amount: 1, unit: "kpl", name: "paprika" },
      { amount: 3, unit: "dl", name: "jasmiiniriisi" },
    ],
    instructions: [
      "Purista tofu kuivaksi ja kuutioi.",
      "Paista tofu pannulla kultaiseksi.",
      "Lisää currypaahto ja paista minuutti.",
      "Kaada kookosmaito ja lisää paprikasuikaleet.",
      "Keitä 10 minuuttia, lisää pinaatti. Tarjoile riisin kanssa.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 4,
    calories: 380,
    proteinGrams: 18,
    carbsGrams: 40,
    fatGrams: 20,
    imageUrl: null,
  },
  {
    name: "Linssikeitto",
    description: "Täyteläinen punainen linssikeitto",
    dietCategory: "vegaani",
    mealType: "lounas",
    ingredients: [
      { amount: 3, unit: "dl", name: "punaiset linssit" },
      { amount: 1, unit: "kpl", name: "sipuli" },
      { amount: 2, unit: "kpl", name: "porkkana" },
      { amount: 2, unit: "kynsi", name: "valkosipuli" },
      { amount: 1, unit: "tl", name: "juustokumina" },
      { amount: 8, unit: "dl", name: "kasvisliemi" },
      { amount: 1, unit: "rkl", name: "sitruunamehu" },
    ],
    instructions: [
      "Kuullota sipuli ja valkosipuli öljyssä.",
      "Lisää pilkotut porkkanat ja mausteet.",
      "Lisää linssit ja kasvisliemi.",
      "Keitä 20 minuuttia kunnes linssit ovat pehmeitä.",
      "Soseuta halutessasi. Lisää sitruunamehu.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 4,
    calories: 280,
    proteinGrams: 16,
    carbsGrams: 42,
    fatGrams: 4,
    imageUrl: null,
  },
  {
    name: "Kaura-banaanipuuro",
    description: "Kermainen kaurapuuro banaanilla ja pähkinöillä",
    dietCategory: "vegaani",
    mealType: "aamiainen",
    ingredients: [
      { amount: 1, unit: "dl", name: "kaurahiutale" },
      { amount: 2.5, unit: "dl", name: "kauramaito" },
      { amount: 1, unit: "kpl", name: "banaani" },
      { amount: 1, unit: "rkl", name: "mantelivoi" },
      { amount: 1, unit: "rkl", name: "vaahterasiirappi" },
    ],
    instructions: [
      "Keitä kaurahiutaleet kauramaidossa.",
      "Murskaa puolet banaanista puuron sekaan.",
      "Annostele kulhoon.",
      "Viipaloiti loput banaanista päälle.",
      "Lisää mantelivoi ja vaahterasiirappi.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 5,
    servings: 1,
    calories: 340,
    proteinGrams: 8,
    carbsGrams: 52,
    fatGrams: 12,
    imageUrl: null,
  },
  {
    name: "Falafel-bowl",
    description: "Falafel riisin ja kasvisten kanssa",
    dietCategory: "vegaani",
    mealType: "lounas",
    ingredients: [
      { amount: 8, unit: "kpl", name: "falafel (valmis)" },
      { amount: 2, unit: "dl", name: "riisi" },
      { amount: 1, unit: "kpl", name: "kurkku" },
      { amount: 100, unit: "g", name: "kirsikkatomaatit" },
      { amount: 2, unit: "rkl", name: "hummus" },
      { amount: 1, unit: "dl", name: "punasipuli" },
    ],
    instructions: [
      "Keitä riisi ja anna jäähtyä hieman.",
      "Lämmitä falafelit uunissa.",
      "Pilko kurkku ja tomaatit.",
      "Kokoa bowl: riisi, kasvikset, falafel.",
      "Lisää hummus päälle.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    calories: 420,
    proteinGrams: 16,
    carbsGrams: 58,
    fatGrams: 14,
    imageUrl: null,
  },
  {
    name: "Kasvispasta pesto",
    description: "Täysjyväpasta vegaanipestolla ja paahdettuja kasviksia",
    dietCategory: "vegaani",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "täysjyväpasta" },
      { amount: 200, unit: "g", name: "kirsikkatomaatit" },
      { amount: 1, unit: "kpl", name: "kesäkurpitsa" },
      { amount: 3, unit: "rkl", name: "vegaanipesto" },
      { amount: 2, unit: "rkl", name: "oliiviöljy" },
      { amount: 50, unit: "g", name: "pinjansiemen" },
    ],
    instructions: [
      "Keitä pasta al denteksi.",
      "Paahda halkaistut tomaatit ja kesäkurpitsaviipaleet uunissa 200°C.",
      "Sekoita pasta ja pesto.",
      "Lisää paahdetut kasvikset.",
      "Ripottele pinjansiemenet päälle.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 4,
    calories: 400,
    proteinGrams: 14,
    carbsGrams: 56,
    fatGrams: 16,
    imageUrl: null,
  },
  {
    name: "Chiapuuro",
    description: "Yön yli tekeytynen chiapuuro marjoilla",
    dietCategory: "vegaani",
    mealType: "aamiainen",
    ingredients: [
      { amount: 3, unit: "rkl", name: "chiansiemen" },
      { amount: 2, unit: "dl", name: "kauramaito" },
      { amount: 1, unit: "rkl", name: "vaahterasiirappi" },
      { amount: 1, unit: "dl", name: "vadelma" },
      { amount: 1, unit: "rkl", name: "kookoshiutale" },
    ],
    instructions: [
      "Sekoita chiansiemenet, kauramaito ja vaahterasiirappi.",
      "Laita jääkaappiin yöksi (vähintään 4 tuntia).",
      "Sekoita aamulla.",
      "Lisää vadelmat ja kookoshiutaleet päälle.",
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 290,
    proteinGrams: 8,
    carbsGrams: 34,
    fatGrams: 14,
    imageUrl: null,
  },

  // === VEGAANI VÄLIPALAT ===
  {
    name: "Pähkinäsekoitus",
    description: "Energia-pähkinäsekoitus kuivatuilla hedelmillä",
    dietCategory: "vegaani",
    mealType: "välipala",
    ingredients: [
      { amount: 30, unit: "g", name: "cashewpähkinä" },
      { amount: 30, unit: "g", name: "manteli" },
      { amount: 20, unit: "g", name: "kuivattu karpalo" },
      { amount: 10, unit: "g", name: "kookoshiutale" },
    ],
    instructions: [
      "Sekoita kaikki ainekset kulhoon.",
      "Nauti sellaisenaan.",
    ],
    prepTimeMinutes: 1,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 240,
    proteinGrams: 7,
    carbsGrams: 18,
    fatGrams: 17,
    imageUrl: null,
  },
  {
    name: "Hummus ja rieska",
    description: "Kaura-rieska hummuksen kanssa",
    dietCategory: "vegaani",
    mealType: "välipala",
    ingredients: [
      { amount: 1, unit: "kpl", name: "kaura-rieska" },
      { amount: 3, unit: "rkl", name: "hummus" },
      { amount: 0.5, unit: "kpl", name: "paprika" },
    ],
    instructions: [
      "Levitä hummus rieskan päälle.",
      "Lisää paprikasuikaleet.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 200,
    proteinGrams: 8,
    carbsGrams: 26,
    fatGrams: 8,
    imageUrl: null,
  },
  {
    name: "Banaani-kaakao smoothie",
    description: "Kermainen vegaanismoothie kaakolla",
    dietCategory: "vegaani",
    mealType: "iltapala",
    ingredients: [
      { amount: 1, unit: "kpl", name: "banaani" },
      { amount: 2, unit: "dl", name: "kauramaito" },
      { amount: 1, unit: "rkl", name: "kaakaojauhe" },
      { amount: 1, unit: "rkl", name: "mantelivoi" },
    ],
    instructions: [
      "Laita kaikki ainekset tehosekoittimeen.",
      "Sekoita tasaiseksi.",
      "Tarjoile heti.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 250,
    proteinGrams: 6,
    carbsGrams: 36,
    fatGrams: 10,
    imageUrl: null,
  },
  {
    name: "Kauraenergiapatukat",
    description: "Kotitekoiset energiapatukat kaurasta",
    dietCategory: "vegaani",
    mealType: "iltapala",
    ingredients: [
      { amount: 2, unit: "dl", name: "kaurahiutale" },
      { amount: 2, unit: "rkl", name: "maapähkinävoi" },
      { amount: 2, unit: "rkl", name: "vaahterasiirappi" },
      { amount: 1, unit: "rkl", name: "chiansiemen" },
    ],
    instructions: [
      "Sekoita kaikki ainekset kulhoon.",
      "Painele tasaiseksi kerrokseksi vuokaan.",
      "Laita jääkaappiin 30 minuutiksi.",
      "Leikkaa paloiksi.",
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 4,
    calories: 180,
    proteinGrams: 5,
    carbsGrams: 24,
    fatGrams: 8,
    imageUrl: null,
  },

  // === KETO ===
  {
    name: "Lohta ja avokadoa",
    description: "Uunilohi avokadosalaatin kanssa",
    dietCategory: "keto",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "lohifilee" },
      { amount: 2, unit: "kpl", name: "avokado" },
      { amount: 1, unit: "kpl", name: "sitruuna" },
      { amount: 2, unit: "rkl", name: "oliiviöljy" },
      { amount: 100, unit: "g", name: "rucola" },
      { amount: 50, unit: "g", name: "pinjansiemen" },
    ],
    instructions: [
      "Mausta lohi suolalla ja pippurilla.",
      "Paista uunissa 200°C noin 15 minuuttia.",
      "Viipaloiti avokadot ja asettele rucolalle.",
      "Puristele sitruunamehua päälle.",
      "Tarjoile lohi salaatin kanssa.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    calories: 520,
    proteinGrams: 34,
    carbsGrams: 6,
    fatGrams: 42,
    imageUrl: null,
  },
  {
    name: "Avokadosalaatti pekonilla",
    description: "Rapea pekonisalaatti avokadolla ja kananmunalla",
    dietCategory: "keto",
    mealType: "lounas",
    ingredients: [
      { amount: 150, unit: "g", name: "pekoni" },
      { amount: 2, unit: "kpl", name: "avokado" },
      { amount: 2, unit: "kpl", name: "kananmuna" },
      { amount: 100, unit: "g", name: "jääsalaatti" },
      { amount: 2, unit: "rkl", name: "oliiviöljy" },
      { amount: 1, unit: "rkl", name: "dijonsinappi" },
    ],
    instructions: [
      "Paista pekoni rapeaksi ja murskaa.",
      "Keitä kananmunat 8 minuuttia.",
      "Viipaloiti avokadot ja munat.",
      "Kokoa salaatti ja ripottele pekoni päälle.",
      "Tee kastike oliiviöljystä ja dijonsinapista.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 2,
    calories: 480,
    proteinGrams: 24,
    carbsGrams: 5,
    fatGrams: 42,
    imageUrl: null,
  },
  {
    name: "Munakokkeli ja lohi",
    description: "Täyteläinen munakokkeli savulohella",
    dietCategory: "keto",
    mealType: "aamiainen",
    ingredients: [
      { amount: 3, unit: "kpl", name: "kananmuna" },
      { amount: 50, unit: "g", name: "savulohi" },
      { amount: 1, unit: "rkl", name: "voi" },
      { amount: 1, unit: "rkl", name: "tuorejuusto" },
      { amount: 1, unit: "rkl", name: "tilli" },
    ],
    instructions: [
      "Vatkaa munat ja tuorejuusto.",
      "Sulata voi pannussa miedolla lämmöllä.",
      "Kaada munamassa ja sekoita hitaasti.",
      "Kun kokkeli on vielä pehmeää, lisää savulohi.",
      "Koristele tillillä.",
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    servings: 1,
    calories: 390,
    proteinGrams: 28,
    carbsGrams: 2,
    fatGrams: 30,
    imageUrl: null,
  },
  {
    name: "Kana-pestosalaatti",
    description: "Grillattua kanaa pestolla ja parmesaanilla",
    dietCategory: "keto",
    mealType: "lounas",
    ingredients: [
      { amount: 300, unit: "g", name: "kananrintafilee" },
      { amount: 2, unit: "rkl", name: "pesto" },
      { amount: 50, unit: "g", name: "parmesaani" },
      { amount: 100, unit: "g", name: "salaattisekoitus" },
      { amount: 100, unit: "g", name: "kirsikkatomaatit" },
      { amount: 2, unit: "rkl", name: "oliiviöljy" },
    ],
    instructions: [
      "Grillaa kananrinnat pannulla kypsiksi.",
      "Viipaleoi kana.",
      "Kokoa salaatti ja asettele kana päälle.",
      "Lusikoi pesto kanan päälle.",
      "Höylää parmesaani ja valuta oliiviöljy.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    calories: 440,
    proteinGrams: 38,
    carbsGrams: 4,
    fatGrams: 32,
    imageUrl: null,
  },
  {
    name: "Voi-yrttilohi",
    description: "Pannulohi yrttivoin kanssa",
    dietCategory: "keto",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "lohifilee" },
      { amount: 50, unit: "g", name: "voi" },
      { amount: 2, unit: "kynsi", name: "valkosipuli" },
      { amount: 2, unit: "rkl", name: "tuore persilja" },
      { amount: 200, unit: "g", name: "parsakaali" },
      { amount: 1, unit: "rkl", name: "oliiviöljy" },
    ],
    instructions: [
      "Paista lohi nahkapuoli ensin pannulla.",
      "Sulata voi erillisellä pannulla, lisää valkosipuli ja persilja.",
      "Höyrytä parsakaali kypsäksi.",
      "Kaada yrttivoi lohen päälle.",
      "Tarjoile parsakaalin kanssa.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    servings: 2,
    calories: 490,
    proteinGrams: 36,
    carbsGrams: 4,
    fatGrams: 38,
    imageUrl: null,
  },
  {
    name: "Voipähkinäsmoothie",
    description: "Pähkinäinen keto-smoothie",
    dietCategory: "keto",
    mealType: "aamiainen",
    ingredients: [
      { amount: 2, unit: "rkl", name: "maapähkinävoi" },
      { amount: 2, unit: "dl", name: "mantelijuoma" },
      { amount: 1, unit: "rkl", name: "kaakaojauhe" },
      { amount: 1, unit: "dl", name: "kerma" },
      { amount: 1, unit: "rkl", name: "chiansiemen" },
    ],
    instructions: [
      "Laita kaikki ainekset tehosekoittimeen.",
      "Sekoita tasaiseksi.",
      "Tarjoile heti.",
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 380,
    proteinGrams: 12,
    carbsGrams: 8,
    fatGrams: 34,
    imageUrl: null,
  },

  // === KETO VÄLIPALAT ===
  {
    name: "Juustopalat ja oliivit",
    description: "Rasvainen keto-välipala",
    dietCategory: "keto",
    mealType: "välipala",
    ingredients: [
      { amount: 80, unit: "g", name: "cheddar-juusto" },
      { amount: 50, unit: "g", name: "oliivit" },
      { amount: 30, unit: "g", name: "macadamiapähkinä" },
    ],
    instructions: [
      "Leikkaa juusto kuutioiksi.",
      "Annostele lautaselle oliivien ja pähkinöiden kanssa.",
    ],
    prepTimeMinutes: 2,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 340,
    proteinGrams: 18,
    carbsGrams: 3,
    fatGrams: 30,
    imageUrl: null,
  },
  {
    name: "Avokadopuolikkaat",
    description: "Avokado suolalla ja sitruunalla",
    dietCategory: "keto",
    mealType: "välipala",
    ingredients: [
      { amount: 1, unit: "kpl", name: "avokado" },
      { amount: 1, unit: "rkl", name: "oliiviöljy" },
      { amount: 1, unit: "tl", name: "sitruunamehu" },
    ],
    instructions: [
      "Halkaisi avokado ja poista kivi.",
      "Loruta oliiviöljy ja sitruunamehu.",
      "Mausta suolalla.",
    ],
    prepTimeMinutes: 2,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 280,
    proteinGrams: 3,
    carbsGrams: 4,
    fatGrams: 28,
    imageUrl: null,
  },
  {
    name: "Juustokääröt kinkulla",
    description: "Juustoviipale kinkkurullana iltapalaksi",
    dietCategory: "keto",
    mealType: "iltapala",
    ingredients: [
      { amount: 3, unit: "viipale", name: "emmental" },
      { amount: 3, unit: "viipale", name: "kinkku" },
      { amount: 1, unit: "rkl", name: "dijonsinappi" },
    ],
    instructions: [
      "Aseta kinkkuviipale juuston päälle.",
      "Sivele sinappia.",
      "Kääri rullaksi.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 260,
    proteinGrams: 20,
    carbsGrams: 2,
    fatGrams: 20,
    imageUrl: null,
  },
  {
    name: "Sellerikepit ja tuorejuusto",
    description: "Rapeat sellerikepit tuorejuustodippillä",
    dietCategory: "keto",
    mealType: "iltapala",
    ingredients: [
      { amount: 3, unit: "varsi", name: "selleri" },
      { amount: 3, unit: "rkl", name: "tuorejuusto" },
      { amount: 1, unit: "tl", name: "ruohosipuli" },
    ],
    instructions: [
      "Leikkaa sellerit tikuiksi.",
      "Sekoita tuorejuusto ja ruohosipuli.",
      "Dippaile.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 120,
    proteinGrams: 4,
    carbsGrams: 3,
    fatGrams: 10,
    imageUrl: null,
  },

  // === PROTEIINI ===
  {
    name: "Kanafajitas",
    description: "Mausteinen kanafajitas kasviksilla",
    dietCategory: "proteiini",
    mealType: "päivällinen",
    ingredients: [
      { amount: 500, unit: "g", name: "kananrintafilee" },
      { amount: 2, unit: "kpl", name: "paprika" },
      { amount: 1, unit: "kpl", name: "sipuli" },
      { amount: 4, unit: "kpl", name: "tortilla" },
      { amount: 2, unit: "rkl", name: "fajitamauste" },
      { amount: 100, unit: "g", name: "raejuusto" },
    ],
    instructions: [
      "Leikkaa kana suikaleiksi ja mausta fajitamausteella.",
      "Paista kana kuumalla pannulla.",
      "Lisää paprika- ja sipulisuikaleet.",
      "Lämmitä tortillat.",
      "Kokoa fajitas: kana, kasvikset ja raejuusto.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 4,
    calories: 420,
    proteinGrams: 42,
    carbsGrams: 32,
    fatGrams: 12,
    imageUrl: null,
  },
  {
    name: "Rahkawrap",
    description: "Proteiinipitoinen wrap rahkalla ja kanalla",
    dietCategory: "proteiini",
    mealType: "lounas",
    ingredients: [
      { amount: 200, unit: "g", name: "grillattua kanaa" },
      { amount: 200, unit: "g", name: "maitorahka" },
      { amount: 2, unit: "kpl", name: "täysjyvätortilla" },
      { amount: 1, unit: "kpl", name: "kurkku" },
      { amount: 100, unit: "g", name: "salaatti" },
      { amount: 1, unit: "rkl", name: "sriracha" },
    ],
    instructions: [
      "Sekoita rahka ja sriracha.",
      "Levitä rahkaseos tortillan päälle.",
      "Lisää kanasuikaleet, kurkku ja salaatti.",
      "Kääri tiiviiksi wrapiksi.",
      "Halkaisi ja tarjoile.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 2,
    calories: 380,
    proteinGrams: 40,
    carbsGrams: 30,
    fatGrams: 10,
    imageUrl: null,
  },
  {
    name: "Proteiinipuuro",
    description: "Kaurapuuro proteiinijauheella ja marjoilla",
    dietCategory: "proteiini",
    mealType: "aamiainen",
    ingredients: [
      { amount: 1, unit: "dl", name: "kaurahiutale" },
      { amount: 2.5, unit: "dl", name: "maito" },
      { amount: 30, unit: "g", name: "proteiinijauhe (vanilja)" },
      { amount: 1, unit: "dl", name: "mustikka" },
      { amount: 1, unit: "rkl", name: "mantelivoi" },
    ],
    instructions: [
      "Keitä kaurapuuro maidossa.",
      "Anna jäähtyä hieman ja sekoita proteiinijauhe.",
      "Annostele kulhoon.",
      "Lisää mustikat ja mantelivoi päälle.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 5,
    servings: 1,
    calories: 380,
    proteinGrams: 32,
    carbsGrams: 38,
    fatGrams: 12,
    imageUrl: null,
  },
  {
    name: "Tonnikala-riisikulho",
    description: "Yksinkertainen tonnikalakulho riisillä ja kasviksilla",
    dietCategory: "proteiini",
    mealType: "lounas",
    ingredients: [
      { amount: 2, unit: "prk", name: "tonnikala vedessä" },
      { amount: 3, unit: "dl", name: "riisi" },
      { amount: 1, unit: "kpl", name: "avokado" },
      { amount: 1, unit: "kpl", name: "kurkku" },
      { amount: 2, unit: "rkl", name: "soijakastike" },
      { amount: 1, unit: "rkl", name: "seesaminsiemen" },
    ],
    instructions: [
      "Keitä riisi ja anna jäähtyä.",
      "Valuta tonnikala.",
      "Viipaloiti avokado ja kurkku.",
      "Kokoa kulho: riisi, tonnikala, kasvikset.",
      "Mausta soijakastikkeella ja ripottele seesaminsiemenet.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    calories: 440,
    proteinGrams: 38,
    carbsGrams: 48,
    fatGrams: 12,
    imageUrl: null,
  },
  {
    name: "Kalkkunapihvi ja bataatti",
    description: "Grillattu kalkkunapihvi bataattilohkojen kanssa",
    dietCategory: "proteiini",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "kalkkunanrintafilee" },
      { amount: 2, unit: "kpl", name: "bataatti" },
      { amount: 200, unit: "g", name: "parsakaali" },
      { amount: 2, unit: "rkl", name: "oliiviöljy" },
      { amount: 1, unit: "tl", name: "paprikajauhe" },
    ],
    instructions: [
      "Leikkaa bataatit lohkoiksi, öljyä ja mausta.",
      "Paista uunissa 200°C 25 minuuttia.",
      "Mausta kalkkunapihvit ja grillaa pannulla.",
      "Höyrytä parsakaali.",
      "Tarjoile yhdessä.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 2,
    calories: 460,
    proteinGrams: 44,
    carbsGrams: 40,
    fatGrams: 14,
    imageUrl: null,
  },
  {
    name: "Kreikkalainen jogurtti ja granola",
    description: "Proteiinipitoinen kreikkalainen jogurtti granolalla",
    dietCategory: "proteiini",
    mealType: "aamiainen",
    ingredients: [
      { amount: 2, unit: "dl", name: "kreikkalainen jogurtti" },
      { amount: 0.5, unit: "dl", name: "granola" },
      { amount: 1, unit: "dl", name: "mansikka" },
      { amount: 1, unit: "rkl", name: "hunaja" },
      { amount: 1, unit: "rkl", name: "chiansiemen" },
    ],
    instructions: [
      "Annostele jogurtti kulhoon.",
      "Lisää granola ja marjat.",
      "Ripottele chiansiemenet päälle.",
      "Loruta hunaja ja tarjoile.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 320,
    proteinGrams: 24,
    carbsGrams: 36,
    fatGrams: 10,
    imageUrl: null,
  },
  // === PROTEIINI VÄLIPALAT ===
  {
    name: "Proteiinirahka",
    description: "Rahka proteiinijauheella ja marjoilla",
    dietCategory: "proteiini",
    mealType: "välipala",
    ingredients: [
      { amount: 2, unit: "dl", name: "maitorahka" },
      { amount: 15, unit: "g", name: "proteiinijauhe" },
      { amount: 1, unit: "dl", name: "mansikka" },
    ],
    instructions: [
      "Sekoita rahka ja proteiinijauhe.",
      "Lisää marjat päälle.",
    ],
    prepTimeMinutes: 2,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 200,
    proteinGrams: 30,
    carbsGrams: 14,
    fatGrams: 3,
    imageUrl: null,
  },
  {
    name: "Kananmuna-avokado",
    description: "Keitetty kananmuna avokadolla",
    dietCategory: "proteiini",
    mealType: "välipala",
    ingredients: [
      { amount: 2, unit: "kpl", name: "kananmuna" },
      { amount: 0.5, unit: "kpl", name: "avokado" },
    ],
    instructions: [
      "Keitä kananmunat 8 minuuttia.",
      "Halkaisi avokado.",
      "Tarjoile yhdessä.",
    ],
    prepTimeMinutes: 2,
    cookTimeMinutes: 8,
    servings: 1,
    calories: 250,
    proteinGrams: 16,
    carbsGrams: 4,
    fatGrams: 20,
    imageUrl: null,
  },
  {
    name: "Raejuusto ja hedelmät",
    description: "Raejuusto banaanin ja hunajan kera",
    dietCategory: "proteiini",
    mealType: "iltapala",
    ingredients: [
      { amount: 2, unit: "dl", name: "raejuusto" },
      { amount: 1, unit: "kpl", name: "banaani" },
      { amount: 1, unit: "rkl", name: "hunaja" },
    ],
    instructions: [
      "Annostele raejuusto kulhoon.",
      "Viipaloiti banaani päälle.",
      "Loruta hunaja.",
    ],
    prepTimeMinutes: 2,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 230,
    proteinGrams: 22,
    carbsGrams: 30,
    fatGrams: 3,
    imageUrl: null,
  },
  {
    name: "Tonnikalaleipä",
    description: "Proteiinipitoinen tonnikalaleipä",
    dietCategory: "proteiini",
    mealType: "iltapala",
    ingredients: [
      { amount: 1, unit: "prk", name: "tonnikala vedessä" },
      { amount: 1, unit: "viipale", name: "täysjyväleipä" },
      { amount: 1, unit: "rkl", name: "majoneesi" },
      { amount: 0.5, unit: "kpl", name: "kurkku" },
    ],
    instructions: [
      "Valuta tonnikala ja sekoita majoneesiin.",
      "Levitä leivän päälle.",
      "Lisää kurkkuviipaleet.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 240,
    proteinGrams: 24,
    carbsGrams: 18,
    fatGrams: 8,
    imageUrl: null,
  },
];

// Assign IDs
export const RECIPES: Recipe[] = allRecipes.map((r, i) => ({
  ...r,
  id: i + 1,
}));

// Generate meal plan
const ALL_MEAL_TYPES: MealType[] = [
  "aamiainen",
  "lounas",
  "välipala",
  "päivällinen",
  "iltapala",
];
const CATEGORIES: DietCategory[] = [
  "kasvisruoka",
  "liharuoka",
  "vegaani",
  "keto",
  "proteiini",
];

export interface MealPlanEntry {
  id: number;
  dietCategory: DietCategory;
  weekNumber: number;
  year: number;
  dayOfWeek: number;
  mealType: MealType;
  recipeId: number;
  recipe: Recipe;
}

function generateWeekMealPlan(
  weekNumber: number,
  year: number
): MealPlanEntry[] {
  const entries: MealPlanEntry[] = [];
  let id = weekNumber * 10000 + year * 100;

  // Use week number as seed offset so different weeks get different recipes
  const weekOffset = weekNumber + year * 52;

  for (const category of CATEGORIES) {
    const catRecipes = RECIPES.filter((r) => r.dietCategory === category);

    for (let day = 0; day < 7; day++) {
      for (const mealType of ALL_MEAL_TYPES) {
        const pool = catRecipes.filter((r) => r.mealType === mealType);
        if (pool.length === 0) continue;

        const recipe = pool[(day + weekOffset) % pool.length];

        entries.push({
          id: id++,
          dietCategory: category,
          weekNumber,
          year,
          dayOfWeek: day,
          mealType,
          recipeId: recipe.id,
          recipe,
        });
      }
    }
  }

  return entries;
}

// Pre-generate a few weeks around current week
const _cache = new Map<string, MealPlanEntry[]>();

export function getMealPlanForWeek(
  weekNumber: number,
  year: number
): MealPlanEntry[] {
  const key = `${year}-${weekNumber}`;
  if (!_cache.has(key)) {
    _cache.set(key, generateWeekMealPlan(weekNumber, year));
  }
  return _cache.get(key)!;
}
