import type { recipes } from "../schema";

type NewRecipe = typeof recipes.$inferInsert;

export const kasvisruokaRecipes: Omit<NewRecipe, "id" | "createdAt">[] = [
  {
    name: "Pinaattikeitto",
    description: "Kermainen pinaattikeitto kananmunalla",
    dietCategory: "kasvisruoka",
    mealType: "lounas",
    ingredients: [
      { amount: 300, unit: "g", name: "tuore pinaatti" },
      { amount: 1, unit: "kpl", name: "sipuli" },
      { amount: 2, unit: "rkl", name: "voi" },
      { amount: 5, unit: "dl", name: "kasvisliemi" },
      { amount: 2, unit: "dl", name: "kerma" },
      { amount: 2, unit: "kpl", name: "kananmuna" },
    ],
    instructions: [
      "Kuullota pilkottu sipuli voissa kattilassa.",
      "Lisää pinaatti ja kasvisliemi. Keitä 5 minuuttia.",
      "Soseuta sauvasekoittimella tasaiseksi.",
      "Lisää kerma ja mausta suolalla ja pippurilla.",
      "Keitä kananmunat 8 minuuttia, puolita ja aseta keiton päälle.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 4,
    calories: 280,
    proteinGrams: 14,
    carbsGrams: 8,
    fatGrams: 22,
    imageUrl: null,
  },
  {
    name: "Kasvispasta",
    description: "Tomaattinen pasta grillatuilla kasviksilla",
    dietCategory: "kasvisruoka",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "pasta" },
      { amount: 2, unit: "kpl", name: "paprika" },
      { amount: 1, unit: "kpl", name: "kesäkurpitsa" },
      { amount: 200, unit: "g", name: "kirsikkatomaatit" },
      { amount: 2, unit: "rkl", name: "oliiviöljy" },
      { amount: 400, unit: "ml", name: "tomaattimurska" },
      { amount: 100, unit: "g", name: "parmesaani" },
    ],
    instructions: [
      "Keitä pasta pakkauksen ohjeen mukaan.",
      "Leikkaa paprikat ja kesäkurpitsa kuutioiksi.",
      "Paista kasvikset oliiviöljyssä pannulla kuumalla lämmöllä.",
      "Lisää kirsikkatomaatit ja tomaattimurska. Keitä 10 minuuttia.",
      "Sekoita pasta ja kastike. Tarjoile parmesaanin kera.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 4,
    calories: 450,
    proteinGrams: 18,
    carbsGrams: 62,
    fatGrams: 14,
    imageUrl: null,
  },
  {
    name: "Juustomunakas",
    description: "Täyteläinen munakas juustolla ja yrteillä",
    dietCategory: "kasvisruoka",
    mealType: "aamiainen",
    ingredients: [
      { amount: 3, unit: "kpl", name: "kananmuna" },
      { amount: 50, unit: "g", name: "emmental-juusto" },
      { amount: 1, unit: "rkl", name: "voi" },
      { amount: 1, unit: "rkl", name: "tuore tilli" },
      { amount: 1, unit: "dl", name: "maito" },
    ],
    instructions: [
      "Vatkaa munat ja maito keskenään.",
      "Sulata voi pannussa keskilämmöllä.",
      "Kaada munamassa pannuun ja anna hyytyä pohjasta.",
      "Ripottele raastettu juusto ja tilli päälle.",
      "Taita kahtia ja tarjoile heti.",
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    servings: 1,
    calories: 380,
    proteinGrams: 26,
    carbsGrams: 3,
    fatGrams: 30,
    imageUrl: null,
  },
  {
    name: "Kasvis-halloumisalaatti",
    description: "Raikas salaatti grillatulla halloumilla",
    dietCategory: "kasvisruoka",
    mealType: "lounas",
    ingredients: [
      { amount: 200, unit: "g", name: "halloumi" },
      { amount: 200, unit: "g", name: "salaattisekoitus" },
      { amount: 1, unit: "kpl", name: "avokado" },
      { amount: 150, unit: "g", name: "kirsikkatomaatit" },
      { amount: 1, unit: "kpl", name: "kurkku" },
      { amount: 2, unit: "rkl", name: "oliiviöljy" },
      { amount: 1, unit: "rkl", name: "sitruunamehu" },
    ],
    instructions: [
      "Leikkaa halloumi viipaleiksi ja grillaa pannulla kultaiseksi.",
      "Kokoa salaatti lautaselle.",
      "Viipaleoi avokado, tomaatit ja kurkku.",
      "Asettele grillattu halloumi päälle.",
      "Valuta oliiviöljy-sitruunakastike päälle.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 5,
    servings: 2,
    calories: 420,
    proteinGrams: 22,
    carbsGrams: 12,
    fatGrams: 34,
    imageUrl: null,
  },
  {
    name: "Kasviscurry",
    description: "Kookoskermalla maustettu kasvis-curry",
    dietCategory: "kasvisruoka",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "kukkakaali" },
      { amount: 2, unit: "kpl", name: "peruna" },
      { amount: 200, unit: "g", name: "pinaatti" },
      { amount: 400, unit: "ml", name: "kookosmaito" },
      { amount: 2, unit: "rkl", name: "currypaahto" },
      { amount: 3, unit: "dl", name: "riisi" },
    ],
    instructions: [
      "Pilko kukkakaali ja perunat kuutioiksi.",
      "Kuullota sipuli ja currypaahto kattilassa.",
      "Lisää kasvikset ja kookosmaito. Keitä 20 minuuttia.",
      "Lisää pinaatti lopussa ja mausta suolalla.",
      "Tarjoile riisin kanssa.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 4,
    calories: 380,
    proteinGrams: 10,
    carbsGrams: 48,
    fatGrams: 18,
    imageUrl: null,
  },
  {
    name: "Rahkapuuro marjoilla",
    description: "Proteiinipitoinen kaurapuuro rahkalla ja marjoilla",
    dietCategory: "kasvisruoka",
    mealType: "aamiainen",
    ingredients: [
      { amount: 1, unit: "dl", name: "kaurahiutale" },
      { amount: 2.5, unit: "dl", name: "vesi" },
      { amount: 1, unit: "dl", name: "rahka" },
      { amount: 1, unit: "dl", name: "mustikka" },
      { amount: 1, unit: "rkl", name: "hunaja" },
    ],
    instructions: [
      "Keitä kaurapuuro vedessä.",
      "Annostele kulhoon ja anna jäähtyä hieman.",
      "Lisää rahka päälle.",
      "Koristele mustikoilla ja hunajalla.",
    ],
    prepTimeMinutes: 2,
    cookTimeMinutes: 5,
    servings: 1,
    calories: 310,
    proteinGrams: 18,
    carbsGrams: 42,
    fatGrams: 8,
    imageUrl: null,
  },
];
