import type { recipes } from "../schema";

type NewRecipe = typeof recipes.$inferInsert;

export const ketoRecipes: Omit<NewRecipe, "id" | "createdAt">[] = [
  {
    name: "Lohta ja avokadoa",
    description: "Uunilohi avokadosalaatin kanssa",
    dietCategory: "keto",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "lohifilee" },
      { amount: 2, unit: "kpl", name: "avokado" },
      { amount: 1, unit: "kpl", name: "sitruuna" },
      { amount: 2, unit: "rkl", name: "oliiviöljy" },
      { amount: 100, unit: "g", name: "rucola" },
      { amount: 50, unit: "g", name: "pinjansiemen" },
    ],
    instructions: [
      "Mausta lohi suolalla ja pippurilla.",
      "Paista uunissa 200°C noin 15 minuuttia.",
      "Viipaloiti avokadot ja asettele rucolalle.",
      "Puristele sitruunamehua päälle.",
      "Tarjoile lohi salaatin kanssa.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    calories: 520,
    proteinGrams: 34,
    carbsGrams: 6,
    fatGrams: 42,
    imageUrl: null,
  },
  {
    name: "Avokadosalaatti pekoniilla",
    description: "Rapea pekonisalaatti avokadolla ja kananmunalla",
    dietCategory: "keto",
    mealType: "lounas",
    ingredients: [
      { amount: 150, unit: "g", name: "pekoni" },
      { amount: 2, unit: "kpl", name: "avokado" },
      { amount: 2, unit: "kpl", name: "kananmuna" },
      { amount: 100, unit: "g", name: "jääsalaatti" },
      { amount: 2, unit: "rkl", name: "oliiviöljy" },
      { amount: 1, unit: "rkl", name: "dijonsinappi" },
    ],
    instructions: [
      "Paista pekoni rapeaksi ja murskaa.",
      "Keitä kananmunat 8 minuuttia.",
      "Viipaloiti avokadot ja munat.",
      "Kokoa salaatti ja ripottele pekoni päälle.",
      "Tee kastike oliiviöljystä ja dijonsinapista.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 2,
    calories: 480,
    proteinGrams: 24,
    carbsGrams: 5,
    fatGrams: 42,
    imageUrl: null,
  },
  {
    name: "Munakokkeli ja lohi",
    description: "Täyteläinen munakokkeli savulohella",
    dietCategory: "keto",
    mealType: "aamiainen",
    ingredients: [
      { amount: 3, unit: "kpl", name: "kananmuna" },
      { amount: 50, unit: "g", name: "savulohi" },
      { amount: 1, unit: "rkl", name: "voi" },
      { amount: 1, unit: "rkl", name: "tuorejuusto" },
      { amount: 1, unit: "rkl", name: "tilli" },
    ],
    instructions: [
      "Vatkaa munat ja tuorejuusto.",
      "Sulata voi pannussa miedolla lämmöllä.",
      "Kaada munamassa ja sekoita hitaasti.",
      "Kun kokkeli on vielä pehmeää, lisää savulohi.",
      "Koristele tillillä.",
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    servings: 1,
    calories: 390,
    proteinGrams: 28,
    carbsGrams: 2,
    fatGrams: 30,
    imageUrl: null,
  },
  {
    name: "Kana-pestosalaatti",
    description: "Grillattua kanaa pestolla ja parmesaanilla",
    dietCategory: "keto",
    mealType: "lounas",
    ingredients: [
      { amount: 300, unit: "g", name: "kananrintafilee" },
      { amount: 2, unit: "rkl", name: "pesto" },
      { amount: 50, unit: "g", name: "parmesaani" },
      { amount: 100, unit: "g", name: "salaattisekoitus" },
      { amount: 100, unit: "g", name: "kirsikkatomaatit" },
      { amount: 2, unit: "rkl", name: "oliiviöljy" },
    ],
    instructions: [
      "Grillaa kananrinnat pannulla kypsiksi.",
      "Viipaleoi kana.",
      "Kokoa salaatti ja asettele kana päälle.",
      "Lusikoi pesto kanan päälle.",
      "Höylää parmesaani ja valuta oliiviöljy.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    calories: 440,
    proteinGrams: 38,
    carbsGrams: 4,
    fatGrams: 32,
    imageUrl: null,
  },
  {
    name: "Voi-yrttilohi",
    description: "Pannulohi yrttivoin kanssa",
    dietCategory: "keto",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "lohifilee" },
      { amount: 50, unit: "g", name: "voi" },
      { amount: 2, unit: "kynsi", name: "valkosipuli" },
      { amount: 2, unit: "rkl", name: "tuore persilja" },
      { amount: 200, unit: "g", name: "parsakaali" },
      { amount: 1, unit: "rkl", name: "oliiviöljy" },
    ],
    instructions: [
      "Paista lohi nahkapuoli ensin pannulla.",
      "Sulata voi erillisellä pannulla, lisää valkosipuli ja persilja.",
      "Höyrytä parsakaali kypsäksi.",
      "Kaada yrttivoi lohen päälle.",
      "Tarjoile parsakaalin kanssa.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    servings: 2,
    calories: 490,
    proteinGrams: 36,
    carbsGrams: 4,
    fatGrams: 38,
    imageUrl: null,
  },
  {
    name: "Voipähkinäsmoothie",
    description: "Pähkinäinen keto-smoothie",
    dietCategory: "keto",
    mealType: "aamiainen",
    ingredients: [
      { amount: 2, unit: "rkl", name: "maapähkinävoi" },
      { amount: 2, unit: "dl", name: "mantelijuoma" },
      { amount: 1, unit: "rkl", name: "kaakaojauhe" },
      { amount: 1, unit: "dl", name: "kerma" },
      { amount: 1, unit: "rkl", name: "chiansiemen" },
    ],
    instructions: [
      "Laita kaikki ainekset tehosekoittimeen.",
      "Sekoita tasaiseksi.",
      "Tarjoile heti.",
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 380,
    proteinGrams: 12,
    carbsGrams: 8,
    fatGrams: 34,
    imageUrl: null,
  },
];
