import type { recipes } from "../schema";

type NewRecipe = typeof recipes.$inferInsert;

export const liharuokaRecipes: Omit<NewRecipe, "id" | "createdAt">[] = [
  {
    name: "Kanawokki",
    description: "Nopea kanawokki kasviksilla ja soijakastikkeella",
    dietCategory: "liharuoka",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "kananrintafilee" },
      { amount: 1, unit: "kpl", name: "paprika" },
      { amount: 1, unit: "kpl", name: "porkkana" },
      { amount: 100, unit: "g", name: "soijaitu" },
      { amount: 3, unit: "rkl", name: "soijakastike" },
      { amount: 1, unit: "rkl", name: "seesaminsiemen" },
      { amount: 3, unit: "dl", name: "riisi" },
    ],
    instructions: [
      "Keitä riisi ohjeen mukaan.",
      "Leikkaa kana suikaleiksi ja paista kuumalla pannulla.",
      "Lisää pilkotut kasvikset ja paista 3 minuuttia.",
      "Mausta soijakastikkeella.",
      "Tarjoile riisin kanssa ja ripottele seesaminsiemenet päälle.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 4,
    calories: 420,
    proteinGrams: 35,
    carbsGrams: 45,
    fatGrams: 10,
    imageUrl: null,
  },
  {
    name: "Lihapullat ja muusi",
    description: "Perinteiset lihapullat kermakastikkeella ja perunamuusilla",
    dietCategory: "liharuoka",
    mealType: "päivällinen",
    ingredients: [
      { amount: 500, unit: "g", name: "jauheliha" },
      { amount: 1, unit: "kpl", name: "kananmuna" },
      { amount: 0.5, unit: "dl", name: "korppujauho" },
      { amount: 1, unit: "dl", name: "maito" },
      { amount: 6, unit: "kpl", name: "peruna" },
      { amount: 2, unit: "dl", name: "kerma" },
    ],
    instructions: [
      "Sekoita jauheliha, muna, korppujauho ja maito.",
      "Muotoile pulliksi ja paista pannulla ruskeiksi.",
      "Keitä perunat ja survoo muusiksi kerman kanssa.",
      "Tee pannuun kermakastike paistinliemestä.",
      "Tarjoile lihapullat muusin ja kastikkeen kanssa.",
    ],
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    servings: 4,
    calories: 520,
    proteinGrams: 32,
    carbsGrams: 38,
    fatGrams: 28,
    imageUrl: null,
  },
  {
    name: "Kinkku-juustoleipä",
    description: "Paahdettu täysjyväleipä kinkkuun ja juustolla",
    dietCategory: "liharuoka",
    mealType: "aamiainen",
    ingredients: [
      { amount: 2, unit: "viipale", name: "täysjyväleipä" },
      { amount: 4, unit: "viipale", name: "kinkku" },
      { amount: 2, unit: "viipale", name: "emmental" },
      { amount: 1, unit: "kpl", name: "tomaatti" },
      { amount: 1, unit: "tl", name: "voi" },
    ],
    instructions: [
      "Paahda leivät ja voitele.",
      "Aseta kinkku ja juusto päälle.",
      "Grillaa kunnes juusto sulaa.",
      "Lisää tomaattiviipaleet ja tarjoile.",
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    servings: 1,
    calories: 380,
    proteinGrams: 24,
    carbsGrams: 30,
    fatGrams: 18,
    imageUrl: null,
  },
  {
    name: "Broilerikeitto",
    description: "Lämmin broilerikeitto juureksilla",
    dietCategory: "liharuoka",
    mealType: "lounas",
    ingredients: [
      { amount: 300, unit: "g", name: "broilerinrintafilee" },
      { amount: 2, unit: "kpl", name: "porkkana" },
      { amount: 2, unit: "kpl", name: "peruna" },
      { amount: 1, unit: "kpl", name: "palsternakka" },
      { amount: 8, unit: "dl", name: "kanaliemi" },
      { amount: 1, unit: "dl", name: "ruokakerma" },
    ],
    instructions: [
      "Keitä broileri liemessä kypsäksi ja revit palasiksi.",
      "Pilko juurekset kuutioiksi ja lisää liemeen.",
      "Keitä kunnes juurekset ovat kypsiä.",
      "Lisää kerma ja broilerin palat takaisin.",
      "Mausta suolalla ja pippurilla.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 4,
    calories: 310,
    proteinGrams: 28,
    carbsGrams: 22,
    fatGrams: 12,
    imageUrl: null,
  },
  {
    name: "Jauheliha-makaronilaatikko",
    description: "Klassinen suomalainen makaronilaatikko",
    dietCategory: "liharuoka",
    mealType: "lounas",
    ingredients: [
      { amount: 400, unit: "g", name: "jauheliha" },
      { amount: 400, unit: "g", name: "makaroni" },
      { amount: 5, unit: "dl", name: "maito" },
      { amount: 3, unit: "kpl", name: "kananmuna" },
      { amount: 1, unit: "kpl", name: "sipuli" },
    ],
    instructions: [
      "Keitä makaronit al denteksi.",
      "Paista jauheliha sipulin kanssa.",
      "Sekoita makaronit ja jauheliha uunivuokaan.",
      "Vatkaa munat ja maito, kaada päälle.",
      "Paista uunissa 200°C noin 40 minuuttia.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 45,
    servings: 6,
    calories: 480,
    proteinGrams: 30,
    carbsGrams: 50,
    fatGrams: 18,
    imageUrl: null,
  },
  {
    name: "Kananmunakokkeli",
    description: "Pehmeä kokkeli tuoreyrteillä",
    dietCategory: "liharuoka",
    mealType: "aamiainen",
    ingredients: [
      { amount: 3, unit: "kpl", name: "kananmuna" },
      { amount: 1, unit: "rkl", name: "voi" },
      { amount: 1, unit: "rkl", name: "ruohosipuli" },
      { amount: 0.5, unit: "dl", name: "maito" },
      { amount: 2, unit: "viipale", name: "ruisleipä" },
    ],
    instructions: [
      "Vatkaa munat ja maito.",
      "Sulata voi pannussa miedolla lämmöllä.",
      "Kaada munamassa ja sekoita hitaasti spatulalla.",
      "Nosta pois tulelta kun kokkeli on vielä hieman pehmeää.",
      "Ripottele ruohosipuli päälle. Tarjoile ruisleivän kanssa.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 5,
    servings: 1,
    calories: 350,
    proteinGrams: 22,
    carbsGrams: 24,
    fatGrams: 20,
    imageUrl: null,
  },
];
