import type { recipes } from "../schema";

type NewRecipe = typeof recipes.$inferInsert;

export const proteiiniRecipes: Omit<NewRecipe, "id" | "createdAt">[] = [
  {
    name: "Kanafajitas",
    description: "Mausteinen kanafajitas kasviksilla",
    dietCategory: "proteiini",
    mealType: "päivällinen",
    ingredients: [
      { amount: 500, unit: "g", name: "kananrintafilee" },
      { amount: 2, unit: "kpl", name: "paprika" },
      { amount: 1, unit: "kpl", name: "sipuli" },
      { amount: 4, unit: "kpl", name: "tortilla" },
      { amount: 2, unit: "rkl", name: "fajitamauste" },
      { amount: 100, unit: "g", name: "raejuusto" },
    ],
    instructions: [
      "Leikkaa kana suikaleiksi ja mausta fajitamausteella.",
      "Paista kana kuumalla pannulla.",
      "Lisää paprika- ja sipulisuikaleet.",
      "Lämmitä tortillat.",
      "Kokoa fajitas: kana, kasvikset ja raejuusto.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 4,
    calories: 420,
    proteinGrams: 42,
    carbsGrams: 32,
    fatGrams: 12,
    imageUrl: null,
  },
  {
    name: "Rahkawrap",
    description: "Proteiinipitoinen wrap rahkalla ja kanalla",
    dietCategory: "proteiini",
    mealType: "lounas",
    ingredients: [
      { amount: 200, unit: "g", name: "grillattua kanaa" },
      { amount: 200, unit: "g", name: "maitorahka" },
      { amount: 2, unit: "kpl", name: "täysjyvätortilla" },
      { amount: 1, unit: "kpl", name: "kurkku" },
      { amount: 100, unit: "g", name: "salaatti" },
      { amount: 1, unit: "rkl", name: "sriracha" },
    ],
    instructions: [
      "Sekoita rahka ja sriracha.",
      "Levitä rahkaseos tortillan päälle.",
      "Lisää kanasuikaleet, kurkku ja salaatti.",
      "Kääri tiiviiksi wrapiksi.",
      "Halkaisi ja tarjoile.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 2,
    calories: 380,
    proteinGrams: 40,
    carbsGrams: 30,
    fatGrams: 10,
    imageUrl: null,
  },
  {
    name: "Proteiinipuuro",
    description: "Kaurapuuro proteiinijauheella ja marjoilla",
    dietCategory: "proteiini",
    mealType: "aamiainen",
    ingredients: [
      { amount: 1, unit: "dl", name: "kaurahiutale" },
      { amount: 2.5, unit: "dl", name: "maito" },
      { amount: 30, unit: "g", name: "proteiinijauhe (vanilja)" },
      { amount: 1, unit: "dl", name: "mustikka" },
      { amount: 1, unit: "rkl", name: "mantelivoi" },
    ],
    instructions: [
      "Keitä kaurapuuro maidossa.",
      "Anna jäähtyä hieman ja sekoita proteiinijauhe.",
      "Annostele kulhoon.",
      "Lisää mustikat ja mantelivoi päälle.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 5,
    servings: 1,
    calories: 380,
    proteinGrams: 32,
    carbsGrams: 38,
    fatGrams: 12,
    imageUrl: null,
  },
  {
    name: "Tonnikala-riisikulho",
    description: "Yksinkertainen tonnikalakulho riisillä ja kasviksilla",
    dietCategory: "proteiini",
    mealType: "lounas",
    ingredients: [
      { amount: 2, unit: "prk", name: "tonnikala vedessä" },
      { amount: 3, unit: "dl", name: "riisi" },
      { amount: 1, unit: "kpl", name: "avokado" },
      { amount: 1, unit: "kpl", name: "kurkku" },
      { amount: 2, unit: "rkl", name: "soijakastike" },
      { amount: 1, unit: "rkl", name: "seesaminsiemen" },
    ],
    instructions: [
      "Keitä riisi ja anna jäähtyä.",
      "Valuta tonnikala.",
      "Viipaloiti avokado ja kurkku.",
      "Kokoa kulho: riisi, tonnikala, kasvikset.",
      "Mausta soijakastikkeella ja ripottele seesaminsiemenet.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    calories: 440,
    proteinGrams: 38,
    carbsGrams: 48,
    fatGrams: 12,
    imageUrl: null,
  },
  {
    name: "Kalkkunapihvi ja bataatti",
    description: "Grillattu kalkkunapihvi bataattilohkojen kanssa",
    dietCategory: "proteiini",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "kalkkunanrintafilee" },
      { amount: 2, unit: "kpl", name: "bataatti" },
      { amount: 200, unit: "g", name: "parsakaali" },
      { amount: 2, unit: "rkl", name: "oliiviöljy" },
      { amount: 1, unit: "tl", name: "paprikajauhe" },
    ],
    instructions: [
      "Leikkaa bataatit lohkoiksi, öljyä ja mausta.",
      "Paista uunissa 200°C 25 minuuttia.",
      "Mausta kalkkunapihvit ja grillaa pannulla.",
      "Höyrytä parsakaali.",
      "Tarjoile yhdessä.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 2,
    calories: 460,
    proteinGrams: 44,
    carbsGrams: 40,
    fatGrams: 14,
    imageUrl: null,
  },
  {
    name: "Kreikkalainen jogurtti ja granola",
    description: "Proteiinipitoinen kreikkalainen jogurtti kotitekoisella granolalla",
    dietCategory: "proteiini",
    mealType: "aamiainen",
    ingredients: [
      { amount: 2, unit: "dl", name: "kreikkalainen jogurtti" },
      { amount: 0.5, unit: "dl", name: "granola" },
      { amount: 1, unit: "dl", name: "mansikka" },
      { amount: 1, unit: "rkl", name: "hunaja" },
      { amount: 1, unit: "rkl", name: "chiansiemen" },
    ],
    instructions: [
      "Annostele jogurtti kulhoon.",
      "Lisää granola ja marjat.",
      "Ripottele chiansiemenet päälle.",
      "Loruta hunaja ja tarjoile.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 320,
    proteinGrams: 24,
    carbsGrams: 36,
    fatGrams: 10,
    imageUrl: null,
  },
];
