import type { recipes } from "../schema";

type NewRecipe = typeof recipes.$inferInsert;

export const vegaaniRecipes: Omit<NewRecipe, "id" | "createdAt">[] = [
  {
    name: "Tofucurry",
    description: "Mausteinen tofucurry kookoskermalla",
    dietCategory: "vegaani",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "kiinteä tofu" },
      { amount: 400, unit: "ml", name: "kookosmaito" },
      { amount: 2, unit: "rkl", name: "currypaahto" },
      { amount: 200, unit: "g", name: "pinaatti" },
      { amount: 1, unit: "kpl", name: "paprika" },
      { amount: 3, unit: "dl", name: "jasmiiniriisi" },
    ],
    instructions: [
      "Purista tofu kuivaksi ja kuutioi.",
      "Paista tofu pannulla kultaiseksi.",
      "Lisää currypaahto ja paista minuutti.",
      "Kaada kookosmaito ja lisää paprikasuikaleet.",
      "Keitä 10 minuuttia, lisää pinaatti. Tarjoile riisin kanssa.",
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 4,
    calories: 380,
    proteinGrams: 18,
    carbsGrams: 40,
    fatGrams: 20,
    imageUrl: null,
  },
  {
    name: "Linssikeitto",
    description: "Täyteläinen punainen linssikeitto",
    dietCategory: "vegaani",
    mealType: "lounas",
    ingredients: [
      { amount: 3, unit: "dl", name: "punaiset linssit" },
      { amount: 1, unit: "kpl", name: "sipuli" },
      { amount: 2, unit: "kpl", name: "porkkana" },
      { amount: 2, unit: "kynsi", name: "valkosipuli" },
      { amount: 1, unit: "tl", name: "juustokumina" },
      { amount: 8, unit: "dl", name: "kasvisliemi" },
      { amount: 1, unit: "rkl", name: "sitruunamehu" },
    ],
    instructions: [
      "Kuullota sipuli ja valkosipuli öljyssä.",
      "Lisää pilkotut porkkanat ja mausteet.",
      "Lisää linssit ja kasvisliemi.",
      "Keitä 20 minuuttia kunnes linssit ovat pehmeitä.",
      "Soseuta halutessasi. Lisää sitruunamehu.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 4,
    calories: 280,
    proteinGrams: 16,
    carbsGrams: 42,
    fatGrams: 4,
    imageUrl: null,
  },
  {
    name: "Kaura-banaanipuuro",
    description: "Kermainen kaurapuuro banaanilla ja pähkinöillä",
    dietCategory: "vegaani",
    mealType: "aamiainen",
    ingredients: [
      { amount: 1, unit: "dl", name: "kaurahiutale" },
      { amount: 2.5, unit: "dl", name: "kauramaito" },
      { amount: 1, unit: "kpl", name: "banaani" },
      { amount: 1, unit: "rkl", name: "mantelivoi" },
      { amount: 1, unit: "rkl", name: "vaahterasiirappi" },
    ],
    instructions: [
      "Keitä kaurahiutaleet kauramaidossa.",
      "Murskaa puolet banaanista puuron sekaan.",
      "Annostele kulhoon.",
      "Viipaloiti loput banaanista päälle.",
      "Lisää mantelivoi ja vaahterasiirappi.",
    ],
    prepTimeMinutes: 3,
    cookTimeMinutes: 5,
    servings: 1,
    calories: 340,
    proteinGrams: 8,
    carbsGrams: 52,
    fatGrams: 12,
    imageUrl: null,
  },
  {
    name: "Falafel-bowl",
    description: "Falafel riisin ja kasvisten kanssa",
    dietCategory: "vegaani",
    mealType: "lounas",
    ingredients: [
      { amount: 8, unit: "kpl", name: "falafel (valmis)" },
      { amount: 2, unit: "dl", name: "riisi" },
      { amount: 1, unit: "kpl", name: "kurkku" },
      { amount: 100, unit: "g", name: "kirsikkatomaatit" },
      { amount: 2, unit: "rkl", name: "hummus" },
      { amount: 1, unit: "dl", name: "punasipuli" },
    ],
    instructions: [
      "Keitä riisi ja anna jäähtyä hieman.",
      "Lämmitä falafelit uunissa.",
      "Pilko kurkku ja tomaatit.",
      "Kokoa bowl: riisi, kasvikset, falafel.",
      "Lisää hummus päälle.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    calories: 420,
    proteinGrams: 16,
    carbsGrams: 58,
    fatGrams: 14,
    imageUrl: null,
  },
  {
    name: "Kasvispasta pesto",
    description: "Täysjyväpasta vegaanipestolla ja paahdettuja kasviksia",
    dietCategory: "vegaani",
    mealType: "päivällinen",
    ingredients: [
      { amount: 400, unit: "g", name: "täysjyväpasta" },
      { amount: 200, unit: "g", name: "kirsikkatomaatit" },
      { amount: 1, unit: "kpl", name: "kesäkurpitsa" },
      { amount: 3, unit: "rkl", name: "vegaanipesto" },
      { amount: 2, unit: "rkl", name: "oliiviöljy" },
      { amount: 50, unit: "g", name: "pinjansiemen" },
    ],
    instructions: [
      "Keitä pasta al denteksi.",
      "Paahda halkaistut tomaatit ja kesäkurpitsavipaleet uunissa 200°C.",
      "Sekoita pasta ja pesto.",
      "Lisää paahdetut kasvikset.",
      "Ripottele pinjansiemenet päälle.",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 4,
    calories: 400,
    proteinGrams: 14,
    carbsGrams: 56,
    fatGrams: 16,
    imageUrl: null,
  },
  {
    name: "Chiapuuro",
    description: "Yön yli tekeytynen chiapuuro marjoilla",
    dietCategory: "vegaani",
    mealType: "aamiainen",
    ingredients: [
      { amount: 3, unit: "rkl", name: "chiansiemen" },
      { amount: 2, unit: "dl", name: "kauramaito" },
      { amount: 1, unit: "rkl", name: "vaahterasiirappi" },
      { amount: 1, unit: "dl", name: "vadelma" },
      { amount: 1, unit: "rkl", name: "kookoshiutale" },
    ],
    instructions: [
      "Sekoita chiansiemenet, kauramaito ja vaahterasiirappi.",
      "Laita jääkaappiin yöksi (vähintään 4 tuntia).",
      "Sekoita aamulla.",
      "Lisää vadelmat ja kookoshiutaleet päälle.",
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    calories: 290,
    proteinGrams: 8,
    carbsGrams: 34,
    fatGrams: 14,
    imageUrl: null,
  },
];
